{"name": "test_error_registration_registered_user", "status": "failed", "statusDetails": {"message": "AssertionError", "trace": "authorization_page = <pages.authorization_page.AuthorizationPage object at 0x0000026DF5A0DAE0>\n\n    def test_error_registration_registered_user(authorization_page):\n        authorization_page.click_to_login_button()\n        authorization_page.click_to_login_w_password_button()\n        authorization_page.click_register_hypertext()\n        authorization_page.set_email_registered_user_registration_form()\n        authorization_page.set_password_registration_form()\n        authorization_page.repeat_password_registration_form()\n        authorization_page.click_first_checkbox_consent_registration_form()\n        authorization_page.scroll_to_register_button_registration_form()\n        authorization_page.click_to_register_button_registration_form()\n>       authorization_page.verify_error_msg_registration()\n\ntests\\test_authorization.py:295: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <pages.authorization_page.AuthorizationPage object at 0x0000026DF5A0DAE0>\n\n    @allure.step('verify message \"The user with this email is already registered\"')\n    def verify_error_msg_registration(self):\n        actual_result = self.get_text_title_of_element(AuthorizationLocators.REGISTRATION_ERROR_MESSAGE)\n>       assert actual_result == 'Пользователь с введенным email уже зарегистрирован'\nE       AssertionError\n\npages\\authorization_page.py:421: AssertionError"}, "steps": [{"name": "clicking to \"Login\" button", "status": "passed", "start": 1690952391399, "stop": 1690952396170}, {"name": "clicking to \"Login with password\" button", "status": "passed", "start": 1690952396170, "stop": 1690952397018}, {"name": "click \"register\" hypertext", "status": "passed", "start": 1690952397018, "stop": 1690952399755}, {"name": "set email in registration form", "status": "passed", "start": 1690952399756, "stop": 1690952400667}, {"name": "set password in registration form", "status": "passed", "start": 1690952400667, "stop": 1690952401176}, {"name": "repeat password in registration form", "status": "passed", "start": 1690952401176, "stop": 1690952401968}, {"name": "click first checkbox of consent in registration form", "status": "passed", "start": 1690952401969, "stop": 1690952402240}, {"name": "scroll the page till the \"register\" button in registration form", "status": "passed", "start": 1690952402240, "stop": 1690952402908}, {"name": "click \"to register\" button in registration form", "status": "passed", "start": 1690952402909, "stop": 1690952404114}, {"name": "verify message \"The user with this email is already registered\"", "status": "failed", "statusDetails": {"message": "AssertionError\n", "trace": "  File \"C:\\Users\\Owner\\PycharmProjects\\LifeHelp\\venv\\lib\\site-packages\\allure_commons\\_allure.py\", line 192, in impl\n    return func(*a, **kw)\n  File \"C:\\Users\\Owner\\PycharmProjects\\LifeHelp\\pages\\authorization_page.py\", line 421, in verify_error_msg_registration\n    assert actual_result == 'Пользователь с введенным email уже зарегистрирован'\n"}, "start": 1690952404114, "stop": 1690952404701}], "start": 1690952391398, "stop": 1690952404702, "uuid": "2574c162-2ae2-45b3-bebb-e9b40da8b7d5", "historyId": "463bc66aec50131aa06269c75df275aa", "testCaseId": "a2b9ab85394460d01f10e217781d9100", "fullName": "tests.test_authorization#test_error_registration_registered_user", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_authorization"}, {"name": "host", "value": "DESKTOP-MNCDD93"}, {"name": "thread", "value": "18012-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_authorization"}]}