{"name": "test_error_authorization_without_set_password", "status": "failed", "statusDetails": {"message": "AssertionError", "trace": "authorization_page = <pages.authorization_page.AuthorizationPage object at 0x000001B37AEA62F0>\n\n    def test_error_authorization_without_set_password(authorization_page):\n        authorization_page.click_to_login_button()\n        authorization_page.click_to_login_w_password_button()\n        authorization_page.set_phone_user_wo_password()\n        authorization_page.set_wrong_password()\n        authorization_page.click_to_authorize_button()\n>       authorization_page.verify_error_msg_authorization_user_wo_password()\n\ntests\\test_authorization.py:329: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <pages.authorization_page.AuthorizationPage object at 0x000001B37AEA62F0>\n\n    @allure.step('verify message \"User has not set the password jet\"')\n    def verify_error_msg_authorization_user_wo_password(self):\n        actual_result = self.get_text_title_of_element(AuthorizationLocators.ERROR_MESSAGE_WRONG_PASSWORD_AUTH_PAGE)\n>       assert actual_result == 'Пароль ранее не был установлен. Пожалуйста, авторизуйтесь с помощью \"Быстрого входа\" ' \\\n                                'и установите пароль в личном кабинете'\nE       AssertionError\n\npages\\authorization_page.py:477: AssertionError"}, "steps": [{"name": "clicking to \"Login\" button", "status": "passed", "start": 1690260498083, "stop": 1690260500750}, {"name": "clicking to \"Login with password\" button", "status": "passed", "start": 1690260500750, "stop": 1690260501021}, {"name": "set phone of user without password for authorization form", "status": "passed", "start": 1690260501022, "stop": 1690260501474}, {"name": "set wrong password", "status": "passed", "start": 1690260501475, "stop": 1690260501839}, {"name": "clicking to \"Authorize\" button", "status": "passed", "start": 1690260501839, "stop": 1690260502015}, {"name": "verify message \"User has not set the password jet\"", "status": "failed", "statusDetails": {"message": "AssertionError\n", "trace": "  File \"C:\\Users\\Owner\\PycharmProjects\\LifeHelp\\venv\\lib\\site-packages\\allure_commons\\_allure.py\", line 192, in impl\n    return func(*a, **kw)\n  File \"C:\\Users\\Owner\\PycharmProjects\\LifeHelp\\pages\\authorization_page.py\", line 477, in verify_error_msg_authorization_user_wo_password\n    assert actual_result == 'Пароль ранее не был установлен. Пожалуйста, авторизуйтесь с помощью \"Быстрого входа\" ' \\\n"}, "start": 1690260502015, "stop": 1690260503157}], "start": 1690260498081, "stop": 1690260503163, "uuid": "eb46e087-ac77-40f0-8c40-c02f38163843", "historyId": "4cef3ca089127203fa3860f3bad1d825", "testCaseId": "825a75ca71ea4071be2a19e94d4a8f6a", "fullName": "tests.test_authorization#test_error_authorization_without_set_password", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_authorization"}, {"name": "host", "value": "DESKTOP-MNCDD93"}, {"name": "thread", "value": "21068-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_authorization"}]}