{"uuid": "1bd90599-6c6e-4912-9c1e-09229540631c", "children": ["eb7e7568-32c6-4f72-b718-75c4bc836cc8"], "befores": [{"name": "setup", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 299.046\n  (Session info: chrome=117.0.5938.134)\nStacktrace:\n\tGetHandleVerifier [0x00007FF793277892+54818]\n\t(No symbol) [0x00007FF7931E6AC2]\n\t(No symbol) [0x00007FF79309DA3B]\n\t(No symbol) [0x00007FF79308C06A]\n\t(No symbol) [0x00007FF79308BFB3]\n\t(No symbol) [0x00007FF79308A82E]\n\t(No symbol) [0x00007FF79308B2EE]\n\t(No symbol) [0x00007FF79309775B]\n\t(No symbol) [0x00007FF7930A84D1]\n\t(No symbol) [0x00007FF7930AC80A]\n\t(No symbol) [0x00007FF79308B937]\n\t(No symbol) [0x00007FF7930A83AA]\n\t(No symbol) [0x00007FF793117609]\n\t(No symbol) [0x00007FF7930FE883]\n\t(No symbol) [0x00007FF7930D3691]\n\t(No symbol) [0x00007FF7930D48D4]\n\tGetHandleVerifier [0x00007FF7935DB992+3610402]\n\tGetHandleVerifier [0x00007FF793631860+3962352]\n\tGetHandleVerifier [0x00007FF793629D4F+3930847]\n\tGetHandleVerifier [0x00007FF793313646+693206]\n\t(No symbol) [0x00007FF7931F1628]\n\t(No symbol) [0x00007FF7931ED934]\n\t(No symbol) [0x00007FF7931EDA62]\n\t(No symbol) [0x00007FF7931DE113]\n\tBaseThreadInitThunk [0x00007FFF50327344+20]\n\tRtlUserThreadStart [0x00007FFF513226B1+33]\n\n", "trace": "  File \"C:\\Users\\Owner\\PycharmProjects\\LifeHelp\\venv\\lib\\site-packages\\pluggy\\_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\Owner\\PycharmProjects\\LifeHelp\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 1129, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\Owner\\PycharmProjects\\LifeHelp\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 901, in call_fixture_func\n    fixture_result = next(generator)\n  File \"C:\\Users\\Owner\\PycharmProjects\\LifeHelp\\conftest.py\", line 43, in setup\n    get_webdriver.get(URL)\n  File \"C:\\Users\\Owner\\PycharmProjects\\LifeHelp\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 353, in get\n    self.execute(Command.GET, {\"url\": url})\n  File \"C:\\Users\\Owner\\PycharmProjects\\LifeHelp\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 344, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\Owner\\PycharmProjects\\LifeHelp\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1696403806931, "stop": 1696404106978}], "start": 1696403806931, "stop": 1696404123424}